version: "3.9"

services:
  api:
    build: .
    tty: true
    restart: "no"
    ports:
        - "8000:8000"
    env_file:
      - .env
    volumes:
      - "./:/api-todos:rw"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
        - "POSTGRES_PASSWORD=secret"
